### ISSUE TITLE
lightsparkplugin doens't work

### ISSUE THREAD

**Issue by aparfenov2** [vasilev/docker-image-palemoon#2]
Hey,
I modified /usr/local/bin/palemooni to
...
${SUDO} docker run -d \
  ${ENV_VARS} \
  ${VOLUMES} \
  ${PALEMOON_EXTRA_DOCKER_ARGUMENTS} \
  vasilev/palemoon:latest-lightsparkplugin-2020-12-21 ${prog} $@ >/dev/null

test WebGL:
https://webglsamples.org/aquarium/aquarium.html
Status: WebGL creation failed: * Refused to create native OpenGL context because of blacklist entry: * Exhausted GL driver options.

could you provide correct run parameters ?

**Comment by vasilev** [comment]
Thank you @kantengri for your interest to Lightspark plugin!

1. You are right, the usage pattern of that experimental Lightspark-enabled image is exactly as in your snippet. You may consider to get more debug logging by disabling Docker's daemon mode and allowing all output to be printed into console:
```
${SUDO} docker run \
  ${ENV_VARS} \
  ${VOLUMES} \
  ${PALEMOON_EXTRA_DOCKER_ARGUMENTS} \
  vasilev/palemoon:latest-lightsparkplugin-2020-12-21 ${prog} $@
```
Also you may want to patch the [cleanup function](https://github.com/vasilev/docker-image-palemoon/blob/28fd84072fc2933334bc6487a33fefb2ddf6feea/scripts/palemoon-wrapper#L35) in the case you do not need old containers for in-depth debugging.

2. I've tested both `vasilev/palemoon:latest-lightsparkplugin-2020-12-21` and just-created `vasilev/palemoon:latest-lightsparkplugin-2021-02-15` on https://webglsamples.org/aquarium/aquarium.html and https://get.webgl.org sites, and both images _work on my machine_ :wink: .

3. As far I understand, WebGL is a technology implemented as essential part of modern browsers, and not related to SWF/Flash in any kind. Both https://webglsamples.org/aquarium/aquarium.html and https://get.webgl.org websites have no SWF content, wherefore the Lightspark plugin is not activated on these sites at all. Also all WebGL examples are able run in my Chromium, which has no plugins.

4. But you've really noticed a strange quirk. I had expected the PaleMoon image without lightsparkplugin (i.e. `vasilev/palemoon:29.0.1`) to work with WebGL, but it did not. It displayed the same error: `Status: WebGL creation failed: * Refused to create native OpenGL context because of blacklist entry: * Exhausted GL driver options.`, and `Error: WebGL: Disallowing antialiased backbuffers due to blacklisting.` (among others) in browser developer console.
I'd suspect the  Lightspark plugin is initializing the OpenGL libraries in some specific manner, magically allowing WebGL to work. Maybe, I'll investigate this quirk later.

Summary:
Looks like subject issue is not related (at least directly) to any of Lightspark or PaleMoon.
I'd prefer to close this issue as unrelated. But feel free to post your ideas if you see a way to patch that WebGL quirk via configuration, startup parameters, or environment variables. Thanks again!
